using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using System.Collections.Generic;
using System.Collections.Immutable;
using static Aspid.MVVM.Generators.Generators.Descriptions.General;

namespace Aspid.MVVM.Generators.Generators.Ids;

public partial class IdGenerator
{
    private static void GenerateCode(
        SourceProductionContext context, 
        ImmutableArray<HashSet<string>> idsList)
    {
        var allIds = new HashSet<string>();
        
        foreach (var ids in idsList)
        {
            foreach (var id in ids)
            {
                allIds.Add(id);
            }
        }
        
        if (allIds.Count is 0) return;
        var code = new CodeWriter();

        code.AppendLine("// <auto-generated>")
            .AppendLine("namespace Aspid.MVVM.Generated")
            .BeginBlock()
            .AppendLine(GeneratedCodeIdAttribute)
            .AppendLine("internal static class Ids")
            .BeginBlock();

        foreach (var id in allIds)
        {
            code.AppendLine(GeneratedCodeIdAttribute)
                .AppendLine($"public const string {id} = \"{id}\";")
                .AppendLine();
        }

        code.EndBlock()
            .EndBlock();

        context.AddSource("Ids", code.GetSourceText());
    }
}